### ISSUE TITLE
Notifications link not showing with the Donut theme

### ISSUE THREAD

**Issue by ShNaYkHs** [q2apro/q2apro-on-site-notifications#11]
I have installed the on-site-notifications plugin from http://www.q2apro.com/plugins/on-site-notifications and it works perfectly for the Snow theme and FlatSnow theme and others themes as weel. However, if I use Donut theme (which is the one that I want to use since it is free nice and responsive), the notification icon does not appear anywhere (on the other themes it appears on the top close to username when logged in).

I don't know if this is a problem with the Donuts theme or with the on-site-notifications plugin, but any help is welcom.

Thank you
Q2A version: 1.7

**Comment by q2apro** [comment]
Please read https://github.com/q2apro/q2apro-on-site-notifications/blob/master/CONTRIBUTING.md before posting issues about other themes: 

> Do you use a custom theme? Maybe this is changing the layout and breaking the plugin. We cannot help you for free with that.
