### ISSUE TITLE
How to fix  Ð´ÐµÐ½ÑŒ Ð½Ð°Ð·Ð°Ð´

### ISSUE THREAD

**Issue by warshipss** [q2apro/q2apro-on-site-notifications#16]
How to fix it?
![5a0cff9c68a9a20939e8ed87ef30b022](https://cloud.githubusercontent.com/assets/16351140/11897951/9974e236-a59c-11e5-9164-3aa06350170b.png)

**Comment by q2apro** [comment]
I have no idea what you are doing, you gave zero information on your setup, no additional information.

**Comment by warshipss** [comment]
1. I downloaded the plugin from your site http://www.q2apro.com/plugins/on-site-notifications
2. I installed the plugin on my site
3.Everything works well, except for an error, as shown in the screenshot
No changes in the plugin files I did not make, did not change the encoding

**Comment by q2apro** [comment]
Still not enough information. Best would be: Give me a link to your site plus a guest login (that you can delete later on).

**Comment by warshipss** [comment]
Ok)
http://warshipsfaq.ru/
test
test

**Comment by q2apro** [comment]
Seems to be an encoding problem. The event time is displayed probably in cyrillic. Server side is everything as it should: https://github.com/q2apro/q2apro-on-site-notifications/blob/master/q2apro-onsitenotifications-page.php#L299

Can you try to add

	header("Content-type: text/html; charset=utf-8");

**before** this line: https://github.com/q2apro/q2apro-on-site-notifications/blob/master/q2apro-onsitenotifications-page.php#L333

	header("Content-type: text/html; charset=utf-8");
	echo $notifyBoxEvents;

Maybe this helps.

**Comment by warshipss** [comment]
It works! Thank you so much!

**Comment by q2apro** [comment]
https://github.com/q2apro/q2apro-on-site-notifications/commit/9898c2dc9fef573ddf03bf5296c74259072f12fe
