### ISSUE TITLE
Critical Vulnerability

### ISSUE THREAD

**Issue by MMargout** [q2apro/q2apro-on-site-notifications#43]
I require a means of contact to disclose information concerning the vulnerability.

**Comment by q2apro** [comment]
Please be so kind and post it here so we can fix it. Thank you.

**Comment by MMargout** [comment]
Exactly! There's no filter, you can even steal sessions from any user just by pasting a simple payload or compromise their history by posting an HTML comment.

Just going to someone's wall and putting: "><script>alert(1)</script> will be executed every time they open the notification, anything after the "> will be included on the page.

**Comment by q2apro** [comment]
Updated: https://github.com/q2apro/q2apro-on-site-notifications/blob/master/q2apro-onsitenotifications-page.php

Hope it's fixed now. 👍

**Comment by MMargout** [comment]
I've checked and the vulnerability has been fixed. Thank you for your prompt attention. :)
