### ISSUE TITLE
Resize windows for mobiles 

### ISSUE THREAD

**Issue by gurjyot** [q2apro/q2apro-on-site-notifications#6]
Your work is worth appraising on this plugin... With your latest updates this plugin is getting it's final shape. 
But the few steps which are remaining for this plugin to be perfect also involve notification window to be of the size for the mobile as new themes are responsive.

**Comment by q2apro** [comment]
https://github.com/q2apro/q2apro-on-site-notifications/commit/e232b13c59cd2be83be2724391f5d0967337b6ae
