### ISSUE TITLE
After changing SnowFlat to FlatBox some warning is showing in admin section

### ISSUE THREAD

**Issue by gurjyot** [q2apro/q2apro-on-site-notifications#9]
I know that it is not your responsibility to develop this theme according to FlatBox. But please help me on this. You told me on an issue before () that by changing SnowFlat to FlatBox, the notification bubble will show perfectly in FlatBox and it did. But due to that change there is a warning being displayed in admin section, how to sought this out.

Warning: Cannot modify header information - headers already sent by (output started at /home3/name/public_html/sitename/qa-include/qa-base.php(568) : eval()'d code:1) in /home3/name/public_html/sitename/qa-include/qa-page.php on line 364

**Comment by q2apro** [comment]
FlatBox is not a theme that comes by the q2a core, contact the FlatBox developer.

**Comment by gurjyot** [comment]
Yes I have changed back to snowflat and the issue was raised an year back. So you can simply close it.
